# Generated by Django 5.1.2 on 2024-10-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('airport', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
