# Generated by Django 5.1.2 on 2024-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('airport', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['depart_time'], 'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
    ]
